export class Client {
    id: number = 0;
    first_name: string | undefined = undefined;
    middle_name: string | undefined = undefined;
    last_name: string | undefined = undefined;
    preferred_name: string | undefined = undefined;
    birth_date: Date | undefined = undefined;
    is_aftercare: boolean = false;
    shoe_size: string | undefined = undefined;
    boot_size: string | undefined = undefined;
    phone: string | undefined = undefined;
    email: string | undefined = undefined;
    status: string | undefined = undefined;
    is_veteran: boolean = false;
    inactive_description: string | undefined = undefined;
    number_meals: number | undefined = undefined;
    joppa_apartment_number: string | undefined = undefined;
    dwelling: string | undefined = undefined;
    created_at: Date = new Date();
    updated_at: Date | undefined = undefined;
    last_interaction_date: Date = new Date();
    gender: string | undefined = undefined;
    race: string | undefined = undefined;
    ethnicity: string | undefined = undefined;
    admin_notes: string | undefined = undefined;
    current_camp_id: number | null = null;
    previous_camp_id: number | null = null;
    number_tanks: number | undefined = undefined;
    number_hoses: number | undefined = undefined;
    household_id: number = 0;
    first_time_homeless: boolean = false;
    date_became_homeless: Date | undefined = undefined;
    homeless_reason: string | undefined = undefined;
    due_to_covid: boolean = false;
    household_relationship_type: string | undefined = undefined;
    client_picture: any = undefined;
    latitude: number | undefined = undefined;
    longitude: number | undefined = undefined;
    has_location: boolean | undefined = undefined;
    diagnosed_mental_physical_disability: boolean | undefined = undefined;
    highest_level_education: string | undefined = undefined;
    city_before_homelessness: string | undefined = undefined;
    state_before_homelessness: string | undefined = undefined;
    hometown: string | undefined = undefined;
    city_grew_up_in: string | undefined = undefined;
    family_currently_lives_in: string | undefined = undefined;
    what_brought_to_des_moines: string | undefined = undefined;
    information_missing_or_unknown: string | undefined = undefined;
    needs_translation: boolean = false;
    translation_language: string | undefined = undefined;
    has_picture: boolean = false; // not a DB column
    hasAttentionNote: boolean = false; // UI/computed property, not a DB column
    hasHeatingEquipment: boolean = false; // UI/computed property, not a DB column
    hasHeatingEquipmentChecked: boolean = false; // UI/computed property to avoid duplicate checks
} 