export class Client {
    id: number = undefined;
    first_name: string = undefined;
    last_name: string = undefined;
    preferred_name: string = undefined;
    birth_date: Date = undefined;
    is_aftercare: boolean = false;
    shoe_size: string = undefined;
    boot_size: string = undefined;
    phone: string = undefined;
    status: string = undefined;
    is_veteran: boolean = false;
    inactive_description: string = undefined;
    number_meals: number = undefined;
    joppa_apartment_number: string = undefined;
    dwelling: string = undefined;
    created_at: Date = undefined;
    updated_at: Date = undefined;
    last_interaction_date: Date = undefined;
    gender: string = undefined;
    admin_notes: string = undefined;
    scene_at: Date = undefined;
    current_camp_id: number = undefined;
    previous_camp_id: number = undefined;
}
