export class LocationCamp {
  id: number = undefined;
  route_id: number = undefined;
  location_id: number = undefined;
  created_at: Date = undefined;
  updated_at: Date = undefined;
  name: string = undefined;
  is_active: boolean = undefined;
  position: number = undefined;
  notes: string = undefined;
  longitude: number = undefined;
  latitude: number = undefined;
  parking_longitude: number = undefined;
  parking_latitude: number = undefined;
  expected_arrival_time: string = undefined;
  admin_notes: string = undefined;
  all_seen: boolean = undefined;
  number_clients_at_camp: number = undefined;
  remain_on_route: boolean = undefined;
  heat_route_only: boolean = undefined;
}
